### ISSUE TITLE
EJS _form 에서 array 처리

### ISSUE THREAD

**Issue by ChangJoo-Park** [ChangJoo-Park/realtime-shop-backend#2]
html 태그의 name에 `[]`를 사용하면 무조건 배열로 전달할 수 있음

**Comment by rkdgusrnrlrl** [comment]
input 테그에 name 값에 `[]` 를 뒤에 붙여 주는 걸 말하시는 건가용 ???

**Comment by ChangJoo-Park** [comment]
`<select name="items[] multiple"></select>`
이런식이에요 ㅋㅋ

그냥 취미로 ejs만 가지고 작업하는데 HTML만 가지고 form 처리하기가 매우 귀찮네요 ㅠ_ㅠ

**Comment by ChangJoo-Park** [comment]
새롭게 알게된건데요

```
<div>
  <select name="items[0][name] multiple"></select>
  <input type="number" name="items[0][amount]">
</div>
<div>
  <select name="items[1][name] multiple"></select>
  <input type="number" name="items[1][amount]">
</div>
```

위처럼하면 request body에  `[ {name: '', amount: 0 }, {name: '', amount: 0 } ]`  이렇게 전달되더라구요
뭐에 홀렸는지 프론트엔드 라이브러리 안쓰고 이상한걸 하고있네요


두 select, input 덩어리에 모두 아무것도 안넣고 하면 각각 키:배열로 전달되요

```
<div>
  <select name="items[][name] multiple"></select>
  <input type="number" name="items[][amount]">
</div>
<div>
  <select name="items[][name] multiple"></select>
  <input type="number" name="items[][amount]">
</div>
```

`[ name: ['', ''], amount: [0, 0]  ]`

**Comment by rkdgusrnrlrl** [comment]
저거 인덱스 되나보네요 ㅎㅎㅎ 저도 저렇게 썼던 기억이 나는데 예제 찾고 있었는데, 예전에 같은 이름의 input 을 순서대로 받아야 되서 썼던것 같아요 ㅎㅎ 필드명도 줄수 있는지는 몰랐네요 덕분에 좋은 정보 얻구갑니다. ㅎㅎㅎ

**Comment by ChangJoo-Park** [comment]
이렇게 생으로 작업하는게 너무 오랜만이라서 괜히 삽질하는거 같아요 ㅋㅋㅋ

**Comment by ChangJoo-Park** [comment]
순수 자바스크립트로 폼 제어하는거 너무 안좋네요 

https://github.com/ChangJoo-Park/realtime-shop-backend/commit/5bd8486d767bd45fd529aa123eb5a40ec598a83a#diff-b82e8b802d333fdcc935eee7cd338075R60

**Comment by ChangJoo-Park** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

client side `<template>`을 사용하는 경우 importNode를 이용해 document fragment에서 NodeElement로 변환가능
